<?php

namespace ContainerGsXPBM3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Cirzq6uService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Cirzq6u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Cirzq6u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userGuard' => ['privates', '.errored..service_locator.Cirzq6u.App\\Entity\\UserGuard', NULL, 'Cannot autowire service ".service_locator.Cirzq6u": it needs an instance of "App\\Entity\\UserGuard" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'userGuard' => 'App\\Entity\\UserGuard',
            'entityManager' => '?',
        ]);
    }
}
