<?php

namespace ContainerOwrfUBY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__1STdxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..1STdx_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..1STdx_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recette' => ['privates', '.errored..service_locator..1STdx_.App\\Entity\\Recette', NULL, 'Cannot autowire service ".service_locator..1STdx_": it needs an instance of "App\\Entity\\Recette" but this type has been excluded in "config/services.yaml".'],
        ], [
            'recette' => 'App\\Entity\\Recette',
        ]);
    }
}
