<?php

namespace ContainerOwrfUBY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ORuGORYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oRuGORY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oRuGORY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ingredient' => ['privates', '.errored..service_locator.oRuGORY.App\\Entity\\Ingredient', NULL, 'Cannot autowire service ".service_locator.oRuGORY": it needs an instance of "App\\Entity\\Ingredient" but this type has been excluded in "config/services.yaml".'],
        ], [
            'ingredient' => 'App\\Entity\\Ingredient',
        ]);
    }
}
