<?php

namespace ContainerNcHsXSX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LUzmbJIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LUzmbJI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LUzmbJI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.jpvOrpT', 'get_ServiceLocator_JpvOrpTService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserGuardController::index' => ['privates', '.service_locator.DnXXwzI', 'get_ServiceLocator_DnXXwzIService', true],
            'App\\Controller\\UserGuardController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserGuardController::show' => ['privates', '.service_locator.seqIyFa', 'get_ServiceLocator_SeqIyFaService', true],
            'App\\Controller\\UserGuardController::edit' => ['privates', '.service_locator.Cirzq6u', 'get_ServiceLocator_Cirzq6uService', true],
            'App\\Controller\\UserGuardController::delete' => ['privates', '.service_locator.Cirzq6u', 'get_ServiceLocator_Cirzq6uService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.jpvOrpT', 'get_ServiceLocator_JpvOrpTService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserGuardController:index' => ['privates', '.service_locator.DnXXwzI', 'get_ServiceLocator_DnXXwzIService', true],
            'App\\Controller\\UserGuardController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserGuardController:show' => ['privates', '.service_locator.seqIyFa', 'get_ServiceLocator_SeqIyFaService', true],
            'App\\Controller\\UserGuardController:edit' => ['privates', '.service_locator.Cirzq6u', 'get_ServiceLocator_Cirzq6uService', true],
            'App\\Controller\\UserGuardController:delete' => ['privates', '.service_locator.Cirzq6u', 'get_ServiceLocator_Cirzq6uService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserGuardController::index' => '?',
            'App\\Controller\\UserGuardController::new' => '?',
            'App\\Controller\\UserGuardController::show' => '?',
            'App\\Controller\\UserGuardController::edit' => '?',
            'App\\Controller\\UserGuardController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserGuardController:index' => '?',
            'App\\Controller\\UserGuardController:new' => '?',
            'App\\Controller\\UserGuardController:show' => '?',
            'App\\Controller\\UserGuardController:edit' => '?',
            'App\\Controller\\UserGuardController:delete' => '?',
        ]);
    }
}
