<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGsXPBM3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGsXPBM3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGsXPBM3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGsXPBM3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGsXPBM3\App_KernelDevDebugContainer([
    'container.build_hash' => 'GsXPBM3',
    'container.build_id' => '57682244',
    'container.build_time' => 1732895919,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGsXPBM3');
