<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOwrfUBY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOwrfUBY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOwrfUBY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOwrfUBY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOwrfUBY\App_KernelDevDebugContainer([
    'container.build_hash' => 'OwrfUBY',
    'container.build_id' => '58b3a0e1',
    'container.build_time' => 1733928657,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOwrfUBY');
